services:
  nginx-server:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    depends_on:
      - springboot-server
    restart: always

  springboot-server:
    build: .
    container_name: springboot-server
    ports:
      - "8080:8080"
    depends_on:
      - mysql-server
    restart: always

  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project2
      MYSQL_USER: project2
      MYSQL_PASSWORD: project2
    restart: always