spring.application.name=project2_java

# db 설정
#docker run -d --name mokgyeokja-mysql -e MYSQL_ROOT_PASSWORD=123456 -e MYSQL_DATABASE=mokgyeokja -p 3307:3306 mysql:8.0
# 위에 줄 복사해서 터미널에 입력 - 새로운 db 서버 생성
# 데이터 소스 생성법
# Host:      localhost
# Port:      3307          ← 도커 컨테이너 포트 (윈도우 MySQL 아님!)
# User:      root
# Password:  123456
# Database:  mokgyeokja

spring.datasource.url=jdbc:mysql://localhost:3307/mokgyeokja
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true