spring.application.name=project2_java

# db ??
#docker run -d --name mokgyeokja-mysql -e MYSQL_ROOT_PASSWORD=123456 -e MYSQL_DATABASE=mokgyeokja -p 3307:3306 mysql:8.0
# ?? ? ???? ???? ?? - ??? db ?? ??
# ??? ?? ???
# Host:      localhost
# Port:      3307          ? ?? ???? ?? (??? MySQL ??!)
# User:      root
# Password:  123456
# Database:  mokgyeokja

spring.datasource.url=jdbc:mysql://localhost:3307/mokgyeokja
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true