name: Deploy Java

on:
  push:
    branches:
      - Developer
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy java to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            set -e

            docker context use default

            cd /home/dw203/server/project2_java
            GIT_SSH_COMMAND='ssh -i ~/.ssh/github_repo_key' git pull origin Developer

            cd /home/dw203/server
            docker compose up -d --build springboot-server
            docker compose up -d --force-recreate nginx-server

            docker builder prune -af || true
            docker image prune -af || true
            df -h
